apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-app
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  strategy: {}
  template:
    metadata:
      labels:
        app: node-app
    spec:
      # imagePullSecrets:
      # - name: registry-credentials

      containers:
      - name: nodejs-demoapp
        image: itzboncar/nodejs-demoapp:1.0
        ports:
        - containerPort: 3000
        resources: {}
status: {}
